/**
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */


/***********************************/
/*    VL53LMZ ULD CNH Data		   */
/***********************************/
/*
* This example how to configure, capture and decode CNH data from
* the VL53L7CH/VL53LCH sensors.
*
* In this example, we also suppose that the number of targets per zone is
* set to 1(see file platform.h).
*/

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "vl53lmz_api.h"
#include "vl53lmz_plugin_cnh.h"

#define RANGING_FREQ 20 //frame rate
#define INTEGRA_TIME 120 //exposure time

#define START_BIN 1
#define NUM_BIN 18
#define MERGE_BIN 1

#define RESOLUTION 8

#define START_X 0
#define START_Y 0

#define MERGE_X 1
#define MERGE_Y 1

#define COLS 8
#define ROWS 8

#define INTENSITY 1
#define DEPTH 0
#define HISTOGRAM 0
#define MULTI_HISTO 0

#define SHARPER 0

int example12(void)
{
	/*********************************/
	/*   VL53LMZ ranging variables  */
	/*********************************/

	uint8_t 				status, isAlive, isReady, i, j;
	VL53LMZ_Configuration 	Dev;					/* Sensor configuration */
	VL53LMZ_ResultsData 	Results;				/* Results data from VL53LMZ */

	VL53LMZ_Motion_Configuration 	cnh_config;		/* Motion Configuration is shared with CNH */

	cnh_data_buffer_t 		cnh_data_buffer;		/* cnh_data_bufer_t is sized to take the largest data transfer  */
													/* possible from the device. If smaller CNH configuration is 	*/
													/* used then cnh_data_buffer size could be make smaller.		*/

	uint32_t 				cnh_data_size;			/* This will be used to record the actual size of CNH data 		*/
													/* generated by the set CNH configuration.						*/

	int agg_id, bin_num;
	float amb_value;
	int bin_value;

	/* variables needed for call to vl53lmz_cnh_get_mem_block_addresses() */
	int32_t					*p_hist = NULL;
	int8_t					*p_hist_scaler = NULL;
	int32_t					*p_ambient = NULL;
	int8_t					*p_ambient_scaler = NULL;

	/*********************************/
	/*      Customer platform        */
	/*********************************/

	/* Fill the platform structure with customer's implementation. For this
	* example, only the I2C address is used.
	*/
	Dev.platform.address = VL53LMZ_DEFAULT_I2C_ADDRESS;

	/* (Optional) Reset sensor toggling PINs (see platform, not in API) */
	//Reset_Sensor(&(Dev.platform));

	/* (Optional) Set a new I2C address if the wanted address is different
	* from the default one (filled with 0x20 for this example).
	*/
	//status = vl53lmz_set_i2c_address(&Dev, 0x20);

	
	/*********************************/
	/*   Power on sensor and init    */
	/*********************************/

	/* (Optional) Check if there is a VL53LMZ sensor connected */
	status = vl53lmz_is_alive(&Dev, &isAlive);
	if(!isAlive || status)
	{
		printf("VL53LMZ not detected at requested address\n");
		return status;
	}

	/* (Mandatory) Initialise the VL53LMZ sensor */
	status = vl53lmz_init(&Dev);
	if(status)
	{
		printf("VL53LMZ ULD Loading failed\n");
		return status;
	}

//	printf("VL53LMZ ULD ready ! (Version : %s)\n",
//			VL53LMZ_API_REVISION);


	status = vl53lmz_set_sharpener_percent(&Dev, SHARPER);
	if(status)
	{
		printf("VL53LMZ set sharper percentage done\n");
		return status;
	}

	/*********************************/
	/*  Set basic ranging settings   */
	/*********************************/
	status = vl53lmz_set_resolution(&Dev, RESOLUTION*RESOLUTION);
	//VL53LMZ_RANGING_MODE_AUTONOMOUS
	//VL53LMZ_RANGING_MODE_CONTINUOUS
	status |= vl53lmz_set_ranging_mode(&Dev, VL53LMZ_RANGING_MODE_CONTINUOUS);
	status |= vl53lmz_set_ranging_frequency_hz(&Dev, RANGING_FREQ);
	status |= vl53lmz_set_integration_time_ms(&Dev, INTEGRA_TIME);
	if(status)
	{
		printf("ERROR - Failed basic configuration sequence, status=%u\n", status);
		return status;
	}


	/*********************************/
	/*  CNH specific configuration   */
	/*********************************/

	/* Populate the basic CNH parameters into the CNH configuration structure */
	status = vl53lmz_cnh_init_config( &cnh_config,
										START_BIN,		/* StartBin 	*/
										NUM_BIN,		/* NumBins   	*/
										MERGE_BIN );	/* SubSample 	*/

	if (status != VL53LMZ_STATUS_OK){
		printf("ERROR at %s(%d) : vl53lmz_cnh_init_config failed : %d\n",__func__, __LINE__,status);
		return status;
	}

	/* Add the aggregate map that maps zones to aggregates. Resolution of map 	*/
	/* must follow that set by vl53lmz_set_resolution(), either 16 or 64 zones.	*/
	status = vl53lmz_cnh_create_agg_map( &cnh_config,
											/* Resolution. Must match value used in vl53lmz_set_resolution() */
											RESOLUTION*RESOLUTION,
											START_X,				/* StartX 		*/
											START_Y,				/* StartY 		*/
											MERGE_X,				/* MergeX		*/
											MERGE_Y,				/* MergeY		*/
											COLS,				    /* Cols			*/
											ROWS );			        /* Rows 		*/
	if (HISTOGRAM && MULTI_HISTO){
		status = vl53lmz_cnh_create_agg_map( &cnh_config,
												/* Resolution. Must match value used in vl53lmz_set_resolution() */
											8*8,
											0,					/* StartX 		*/
											0,					/* StartY 		*/
											1,					/* MergeX		*/
											1,					/* MergeY		*/
											8,				    /* Cols			*/
										    8 );
		/* Rows 		*/
		status = vl53lmz_cnh_init_config( &cnh_config,
											0,		/* StartBin 	*/
											18,	    /* NumBins   	*/
											1 );	/* SubSample 	*/
	}

	if (status != VL53LMZ_STATUS_OK){
		printf("ERROR at %s(%d) : vl53lmz_cnh_create_agg_map failed : %d\n",__func__, __LINE__,status);
		return status;
	}

	/* Check that the requested configuration will not generate CNH data that is 		*/
	/* too large for the available space on the sensor.									*/
	/* Store the size of data generate so we can next setup an optimize data transfer 	*/
	/* from sensor to host.																*/
	status = vl53lmz_cnh_calc_required_memory( &cnh_config, &cnh_data_size );
	if (status != VL53LMZ_STATUS_OK){
		printf("ERROR at %s(%d) : vl53lmz_cnh_calc_required_memory : %d\n",__func__, __LINE__,status);
		if (cnh_data_size < 0){
			printf("Required memory is too high : %lu.	Maximum is %lu!\n", cnh_data_size, VL53LMZ_CNH_MAX_DATA_BYTES);
		}
		return status;
	}

	/* Send this CNH configuration to the sensor.										*/
	status = vl53lmz_cnh_send_config(&Dev,&cnh_config);
	if (status != VL53LMZ_STATUS_OK){
		printf("ERROR at %s(%d) : vl53lmz_cnh_send_config failed : %d\n",__func__, __LINE__,status);
		return status;
	}

	/* Because we want to use a non-standard data transfer from the device we can not   	*/
	/* use the standard vl53lmz_start_ranging() function, instead we need to use  			*/
	/* vl53lmz_create_output_config() followed by vl53lmz_send_output_config_and_start() 	*/
	/* This allows us to modify the data transfer requested between the two functions.		*/

	/* First create the standard data upload(output) configuration. 						*/
	status = vl53lmz_create_output_config(&Dev);
	if (status != VL53LMZ_STATUS_OK){
		printf("ERROR at %s(%d) : vl53lmz_create_output_config failed : %d\n",__func__, __LINE__,status);
		return status;
	}

	/* Next, add the CNH data block, sized correctly for the configuration we are using. */
	union Block_header cnh_data_bh;
	cnh_data_bh.idx = VL53LMZ_CNH_DATA_IDX;
	cnh_data_bh.type = 4;
	cnh_data_bh.size = cnh_data_size / 4;
	status = vl53lmz_add_output_block(&Dev, cnh_data_bh.bytes);
	if (status != VL53LMZ_STATUS_OK){
		printf("ERROR at %s(%d) : vl53lmz_add_output_block failed : %d\n",__func__, __LINE__,status);
		return status;
	}

	/*********************************/
	/*  Start the sensor ranging     */
	/*********************************/

	/* Finally, send the output configuration and start the sensor ranging. */
 	status = vl53lmz_send_output_config_and_start(&Dev);

   	//printf("Started ranging\n");

   	while(1)
   	{
   		status = vl53lmz_check_data_ready(&Dev, &isReady);
   		if(isReady)
   		{
   			vl53lmz_get_ranging_data(&Dev, &Results);
   			/* As the sensor is set in 4x4 mode by default, we have a total of 16 zones */
   			/* to print. This example assumes VL53LMZ_NB_TARGET_PER_ZONE == 1 */

			if(INTENSITY){
   			//printf("Intensity, print data no : %3u\n", Dev.streamcount);
   			for(i = 0; i < COLS; i++)
   			{
   				for (j = 0; j < ROWS; j++)
					{
						printf("%d ", Results.signal_per_spad[VL53LMZ_NB_TARGET_PER_ZONE*j+i*RESOLUTION]);
					}
   				printf("\n");
   			}
   			}

			if(DEPTH){
   			//printf("Depth, print data no : %d\n", Dev.streamcount);
   			for(i = 0; i < COLS; i++)
   			{
   				for (j = 0; j < ROWS; j++)
					{
						printf("%4d ", Results.distance_mm[VL53LMZ_NB_TARGET_PER_ZONE*j+i*RESOLUTION]);
					}
   				printf("\n");
   			}
			}

   			/* Because we use a non-standard upload configuration for CNH data we   */
   			/* must extract the data from the ULD transfer buffer and place it in   */
   			/* our own data area before accessing it.								*/
			if(HISTOGRAM && !MULTI_HISTO){
			status = vl53lmz_results_extract_block( &Dev, VL53LMZ_CNH_DATA_IDX,
													(uint8_t *)cnh_data_buffer, cnh_data_size );
			if (status != VL53LMZ_STATUS_OK){
				printf("ERROR at %s(%d) : vl53lmz_results_extract_block failed : %d\n",__func__, __LINE__,status);
				return status;
			}
				for(agg_id = 0; agg_id < cnh_config.nb_of_aggregates; agg_id++)
				{
					/* Start address of each aggregates data blocks within the cnh_data_buffer depends	*/
					/* on the exact CNH configuration in use. Function below calculates these start 	*/
					/* locations for us.																*/
					vl53lmz_cnh_get_block_addresses( &cnh_config,
														agg_id,
														cnh_data_buffer,
														&(p_hist), &(p_hist_scaler),
														&(p_ambient), &(p_ambient_scaler));

					/* there is just a single ambient value per aggregate */
					amb_value = ((float)*p_ambient)/(2<<*p_ambient_scaler);
					//printf("Agg, %2d, Ambient, % .1f, Bins, ", agg_id, amb_value );
					for( bin_num = 0; bin_num < cnh_config.feature_length; bin_num++ ) {
						bin_value = (p_hist[bin_num])/(2<<p_hist_scaler[bin_num]);
						printf("%d ",bin_value);
					}
					printf("\n");
				}
			}
			if(HISTOGRAM && MULTI_HISTO){
                status = vl53lmz_results_extract_block(&Dev, VL53LMZ_CNH_DATA_IDX,
                                                       (uint8_t *)cnh_data_buffer, cnh_data_size);
                int zone_id;
                if (status != VL53LMZ_STATUS_OK)
                {
                    printf("ERROR: extract_block failed\n");
                    return status;
                }

                for (int zone_y = 0; zone_y < 8; zone_y++)
                {
                    for (int zone_x = 0; zone_x < 8; zone_x++)
                    {
                        zone_id = zone_y * COLS + zone_x;

                        vl53lmz_cnh_get_block_addresses(&cnh_config, zone_id, cnh_data_buffer,
                                                         &p_hist, &p_hist_scaler,
                                                         &p_ambient, &p_ambient_scaler);

                        for (bin_num = 0; bin_num < 18; bin_num++)
                        {
                            bin_value = p_hist[bin_num] / (2 << p_hist_scaler[bin_num]);
                            printf("%d ", bin_value);
                        }
                        printf("\n");
                    }
                }
			}
   		}
		/* Wait a few ms to avoid too high polling (function in platform file, not in API) */
   		WaitMs(&(Dev.platform), 0.1);
   	}

   	status = vl53lmz_stop_ranging(&Dev);
//   	printf("Stop ranging autonomous\n");
//
//   	printf("End of ULD demo\n");
   	return status;
}

